RobokopU24/ORION

Common/utils.py, FooDB/src/loadFDB.py, GOA/src/loadGOA.py, GTEx/src/loadGTEx.py, IntAct/src/loadIA.py, PHAROS/src/loadPHAROS.py, UberGraph/src/loadUG.py, ViralProteome/src/loadUniRef.py, ViralProteome/src/loadVP.py, load_all.py
=> reformatting normlaization log output

IntAct/src/loadIA.py, tests/test_loaders.py
updated code to assign the correct categories on node normalization failures
#25
=> updated code to assign the correct categories on node normalization failures

PHAROS/src/loadPHAROS.py, UberGraph/src/loadUG.py, tests/test_loaders.py
=> final updates to fix the orphan nodes issue

PHAROS/src/loadPHAROS.py
=> addition of provenance to the pharos edges

Common/utils.py, parsers/UberGraph/src/.gitattributes, parsers/UberGraph/src/loadUG.py, parsers/UberGraph/src/properties-nonredundant.zip
this PR realigns the location of the ubergraph hand-curated data source.
=> Ubergraph rawdata get

parsers/PHAROS/src/loadPHAROS.py
numerous fixes to get pharos  creating kgx file properly
=> Pharos fixes

Common/extractor.py, Common/kgx_file_normalizer.py, Common/kgx_file_writer.py, Common/load_manager.py, Common/loader_interface.py, Common/node_types.py, Common/supplementation.py, Common/utils.py, default-sources-spec.yml, parsers/GOA/src/loadGOA.py, parsers/PHAROS/src/loadPHAROS.py, parsers/ViralProteome/src/get_uniref_taxon_indexes.py, parsers/ViralProteome/src/loadVP.py, parsers/biolink/src/loadBL.py
various improvements made by the team
=> Loader and norm improvements

Common/kgx_file_normalizer.py, parsers/PHAROS/src/loadPHAROS.py, parsers/hgnc/src/loadHGNC.py
adjusting values so that when none they do not get represented in the output data.
=> Merge by knowledge source

parsers/PHAROS/src/loadPHAROS.py
see issue: https://github.com/RENCI-AUTOMAT/Data_services/issues/93
=> correcting the parsing of certain edges. 

parsers/PHAROS/src/loadPHAROS.py, parsers/hetio/src/loadHetio.py
hetio fixes to make sure some more predicates normalize proper;y, make MIM curies OMIM so they node normalize properly.
=> Predicate and node fixes

Common/build_manager.py, Common/kgx_file_normalizer.py, Common/kgx_file_writer.py, Common/load_manager.py, Common/loader_interface.py, Common/node_types.py, Common/utils.py, default-graph-spec.yml, parsers/GOA/src/loadGOA.py, parsers/GWASCatalog/src/loadGWASCatalog.py
What you have looks good, but to utilize the rest of the pipeline we need to add PlantGOA as a data source option in the load manager. I went ahead and set that up, so you can focus on overriding anything that is different and specific to the plant source, as shown in the comments. Then when you are happy with the source KGX it creates, you can call it from the load manager to run the whole pipeline. (python Common/load_manager.py -ds PlantGOA)
ps. the TODO comments are not necessarily for you, they are just notes for later
=> Plant goa suggestions

parsers/yeast/src/collectSGDdata.py, parsers/yeast/src/loadYeastSGDInfo.py
Running load_manager.py on loadYeastSGDInfo.py now automatically downloads, cleans, and parses SGD data to load nodes and edges in one step.
=> Yeast epigenetics parser

Common/load_manager.py, parsers/textminingkp/src/loadTMKP.py
The load manager now loads in  only the libraries you use when building the graph with a specific config.
Also added in TextMiningKP loading capabilites.
=> Changed how load manager works to do dynamic loads and added in TextMiningKP

Common/utils.py, parsers/IntAct/src/loadIA.py, parsers/hmdb/src/loadHMDB.py, parsers/panther/src/loadPanther.py, set_up_test_env.sh
- fixing bug with HMDB related to leftover legacy logging set up
- cleaning up other old logging code that shouldn't be there
- minor change to set up test env script, create all required directories by default
=> Logging cleanup

graph_specs/default-graph-spec.yml, parsers/CTD/src/loadCTD.py, tests/test_normalization.py
updating treats predicate for CTD,
updating some normalization tests according to changes in the clingen allele registry
=> Treats refactor

parsers/PHAROS/src/loadPHAROS.py
Modified the assignments for KL and AT for the Jensen Lab Databases 
DOI: https://doi.org/10.1093/database/baac019
resolves #226
=> Improving the KL/AT in Pharos

Common/predicates.py, parsers/BINDING/src/loadBINDINGDB.py, parsers/PHAROS/src/loadPHAROS.py, parsers/drugcentral/src/loaddrugcentral.py, parsers/gtopdb/src/loadGtoPdb.py
Modified predicates to remove depreciated predict biolink:binds. Added comments for future modifications in /Common/predicates.py
resolves RobokopU24/Feedback#219
=> Modified predicates affected by biolink:binds

parsers/monarchkg/src/loadMonarchKG.py
Changed Monarch KG ingest to automatically pull from the latest version. Also made process to check the metadata yaml file for the publishing date of the latest version.
This will resolve #253
=> Made change to make versioning of Monarch KG ingests dynamic.

parsers/CTD/src/loadCTD.py
Made the regex pattern a "raw" string.
=> Fixed regex pattern issue in loadCTD.py

Common/biolink_utils.py
we download the infores catalog from github, this implements some retries and raises a more appropriate exception if/when it does fail
=> retry on failed infores catalog retrieval

celery_worker.py, docker-compose-worker.yml, docker-compose.yml, requirements.txt
@EvanDietzMorris This PR adds ORION worker for Litcoin pipeline integration. I have got it working in my local docker development environment along with LitCoin pipeline containers with code in [the LitCoin repo](https://github.com/ncats/LitCoin/tree/pipeline/pipeline). I am creating this PR to get your input to see if the worker added is generally applicable to other app use cases such as Robokop in addition to the LitCoin app. I will work on getting the pipeline integration working in Sterling next.
=> Added ORION worker for Litcoin pipeline integration

parsers/PHAROS/src/loadPHAROS.py
removed __name__ == '__main__' section
removed TIGA edges
=> Update loadPHAROS.py to remove TIGA edges

parsers/hmdb/src/loadHMDB.py
I've run this on HMDB and it seems to work.  Closes #196 .
=> reviewed and modified gene/metabolite edges

graph_specs/default-graph-spec.yml, graph_specs/matrix-graph-spec.yaml, graph_specs/signor-graph-spec.yml
adding CCIDB to robokopkg
adding a matrix graph spec
=> Graph spec updates
